Map<String, dynamic> flightDemoData = {
  "response": {
    "_id": "68b56e5be3a1f1fe84d2c347",
    "is_placed": true,
    "is_confirmed": true,
    "is_cancelled": false,
    "cancelled_by": "",
    "transid": "25090112582IH",
    "status": "Order Placed",
    "is_paid": true,
    "currency": 1,
    "phone": "255787843151",
    "user_id": "639c07bcccc3c572ec489572",
    "sqr_amount": 0,
    "payment_mode": "Selcom Pay / Mastercard QR",
    "is_checkout": true,
    "total_price": 100,
    "convenience_fees": 0,
    "fare": {
      "currency": "TZS",
      "total": "100",
      "base": "284900",
      "taxes": "144000",
      "fees": "0",
      "service_fee": "0",
      "booking_fee": "",
    },
    "cancel_reason": "",
    "is_refund": 0,
    "ussd_phone_number": "",
    "passenger_info": {
      "mobile": "787843151",
      "email": "Pankaj@selcom.net",
      "info": [
        {
          "prefix": "Mr",
          "fname": "SAFWAN",
          "lname": "BOLWALA",
          "dob": "2013-07-28",
          "nationality": "TZ",
          "pno": "",
          "pissuecountry": "",
          "pexp": "",
          "is_wheel": "0",
          "type": "Adult",
        },
      ],
    },
    "unique_key": "G0RTCPCC6HOH8YWSCHL27SENU",
    "ticket_status": 1,
    "created_on": "2025-09-01T09:58:51.003Z",
    "__v": 0,
    "booking_transaction_id": "452",
    "response_from_ottap": {
      "status": 200,
      "message": "Ticketing successful!",
      "universal_code": "TESTHC",
      "reservation_code": "71TEST",
      "ticket_no": "TEST588545",
      "transacion_id": "452",
      "currency": "TZS",
      "paid_amount": "1000.00",
      "is_prod": "0",
      "reserve_time": "2025-09-01 13:00:38",
      "airline_PNR": "AB12345",
      "ticket_nos": "0313104874009",
    },
    "booking_info": {
      "status": 200,
      "message": "Transaction details found!",
      "error": "200",
      "booking_id": "WV52131874",
      "booking_time": "2023-11-13 16:25:55",
      "pay_type": "Credit/Debit Card",
      "agent_pnr": "64WW04",
      "airline_pnr": "7YZ8WA",
      "flight_class": "Economy",
      "primary_passenger_name": "BENSON MSELI",
      "email": "benson_mseli@wvi.org",
      "phone": "255768192367",
      "amount": "TSH. 402,400.00",
      "convenience_charges": "TSH. 5,900.00",
      "total_amount": "TSH. 408,300.00",
      "flights_info": [
        {
          "start_city": "Kilimanjaro",
          "end_city": "Dar Es Salaam",
          "start_date_time": "2023-11-14 20:20:00",
          "end_date_time": "2023-11-14 22:20:00",
          "carrier_short_name": "TC",
          "carrier_long_name": "Air Tanzania",
          "flight_number": "105",
          "equipment_number": "DH8",
          "dutation": "120",
          "start_terminal": "",
          "end_terminal": "Terminal 2",
          "baggage_info": "1x23 Kilograms",
        },
        {
          "start_city": "Kilimanjaro",
          "end_city": "Zanzibar",
          "start_date_time": "2023-11-14 20:20:00",
          "end_date_time": "2023-11-14 21:20:00",
          "carrier_short_name": "TC",
          "carrier_long_name": "Air Tanzania",
          "flight_number": "105",
          "equipment_number": "DH8",
          "dutation": "60",
          "start_terminal": "",
          "end_terminal": "",
          "baggage_info": "1x23 Kilograms",
        },
        {
          "start_city": "Zanzibar",
          "end_city": "Dar Es Salaam",
          "start_date_time": "2023-11-14 21:50:00",
          "end_date_time": "2023-11-14 22:20:00",
          "carrier_short_name": "TC",
          "carrier_long_name": "Air Tanzania",
          "flight_number": "105",
          "equipment_number": "DH8",
          "dutation": "30",
          "start_terminal": "",
          "end_terminal": "Terminal 2",
          "baggage_info": "1x23 Kilograms",
        },
        {
          "start_city": "Dar Es Salaam",
          "end_city": "Kilimanjaro",
          "start_date_time": "2023-11-17 05:15:00",
          "end_date_time": "2023-11-17 06:25:00",
          "carrier_short_name": "TC",
          "carrier_long_name": "Air Tanzania",
          "flight_number": "134",
          "equipment_number": "DH8",
          "dutation": "70",
          "start_terminal": "Terminal 2",
          "end_terminal": "",
          "baggage_info": "1x23 Kilograms",
        },
      ],
      "passengers_info": [
        {"full_name": "Mr BENSON MSELI", "ticket_number": "1976752114302"},
      ],
      "penalties": [
        {
          "type": "before departure",
          "penalties": ["Cancellations charge TZS 50,000.00"],
        },
        {
          "type": "after departure",
          "penalties": [
            "Cancellations charge TZS 80,000.00",
            "No show charge TZS 80,000.00",
          ],
        },
      ],
    },
  },
  "message": "Data fetched Successfully",
  "status_code": 200,
};
